version: "3"
services:
  features:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    # restart: "always"
    volumes:
      - ".:/app"
    env_file:
      - db_settings.env
      - es_settings.env
    environment:
      - CONSUMER_TOPICS=correction
      - CONSUMER_SERVER=localhost:9092
      - CONSUMER_GROUP_ID=features
      - PRODUCER_TOPIC=features
      - PRODUCER_SERVER=localhost:9092
      - LOGGING_DEBUG=True