version: "3"
services:
  features:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    env_file:
      - db_settings.env
      - es_settings.env
    environment:
      - CONSUMER_TOPICS=
      - CONSUMER_SERVER=
      - CONSUMER_GROUP_ID=
      - PRODUCER_TOPIC=
      - PRODUCER_SERVER=
      - ES_PREFIX=
      - ES_NETWORK_HOST=
      - ES_NETWORK_PORT=
      - DB_HOST=
      - DB_USER=
      - DB_PASSWORD=
      - DB_PORT=
      - DB_NAME=
      - METRICS_HOST=
      - METRICS_TOPIC=
