version: "3"
services:
  feature:
    build: .
    environment:
      - DB_ENGINE=postgres
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - CONSUMER_TOPICS=preprocess
      - CONSUMER_SERVER=${CONSUMER_SERVER}
      - CONSUMER_GROUP_ID=features_consumer_batch_test
      - PRODUCER_TOPIC=features_batch
      - PRODUCER_SERVER=${PRODUCER_SERVER}
      - STEP_VERSION=correction_1.0.1
      - FEATURE_VERSION=features_1.0.1
      - METRICS_HOST=${METRICS_HOST}
      - METRICS_TOPIC=${METRICS_TOPIC}
      - CONSUME_TIMEOUT=60
      - CONSUME_MESSAGES=1000
    volumes:
      - ./:/app
      - /home/camilo/Desktop/alerce/late_classifier:/src/lc-classifier #DELETE
    stdin_open: true
    tty: true
    command: /bin/bash
